-- Tabela de grupos de acesso
CREATE TABLE TB_ACCESS_GROUP (
    ID INT NOT NULL,
    NAME VARCHAR(50) NOT NULL
);

ALTER TABLE TB_ACCESS_GROUP
ADD CONSTRAINT PK_TB_ACCESS_GROUP_ID PRIMARY KEY (ID);

ALTER TABLE TB_ACCESS_GROUP
ADD CONSTRAINT UQ_TB_ACCESS_GROUP_NAME UNIQUE (NAME);

-- Tabela de usuários
CREATE TABLE TB_USERS (
    ID INT IDENTITY(1,1),
    USERNAME NVARCHAR(150) NOT NULL,
    PASSWORD_HASH NVARCHAR(255) NOT NULL,
    ACTIVE CHAR(1) DEFAULT '1',
    ACCESS_GROUP INT NOT NULL,
    CREATED_AT DATETIME DEFAULT GETDATE() NOT NULL,
    UPDATED_AT DATETIME DEFAULT NULL
);

ALTER TABLE TB_USERS
ADD CONSTRAINT PK_TB_USERS_ID PRIMARY KEY (ID);

ALTER TABLE TB_USERS
ADD CONSTRAINT UQ_TB_USERS_USERNAME UNIQUE (USERNAME);

ALTER TABLE TB_USERS
ADD CONSTRAINT FK_TB_USERS_ACCESS_GROUP FOREIGN KEY (ACCESS_GROUP)
REFERENCES TB_ACCESS_GROUP(ID);